apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: mr-cassop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mr-cassop
subjects:
  - kind: ServiceAccount
    name: mr-cassop
    namespace: {{ .Release.Namespace | quote }}
