{
 "title": "Cassandra - Reaper Overview",
 "tags": [
  "cassandra",
  "reaper"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(io_cassandrareaper_management_jmx_JmxManagementConnectionFactory_jmxConnectionsIntializer_count, pod)"
    }
   },
   {
    "name": "runid",
    "label": "runid",
    "query": {
     "query": "label_values(io_cassandrareaper_service_RepairRunner_repairProgress, repairid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Job Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "io_cassandrareaper_service_RepairRunner_repairProgress{pod=~\"$pod\", repairid=~\"$runid\"}",
     "legendFormat": "runid: {{repairid}}"
    }
   ]
  },
  {
   "title": "Last job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(io_cassandrareaper_service_RepairRunner_millisSinceLastRepair{pod=~\"$pod\",repairid=~\"$runid\"}[2m])",
     "legendFormat": "runid: {{repairid}}"
    }
   ]
  },
  {
   "title": "Lead operations",
   "type": "timeseries",
   "description": "Shows Cassandra coordinator releasing operations for segment processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_releaseLead_count{pod=~\"$pod\"}[2m])",
     "legendFormat": "Release lead: {{pod}}"
    },
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_takeLead_count{pod=~\"$pod\"}[2m])",
     "legendFormat": "Take lead: {{pod}}"
    }
   ]
  },
  {
   "title": "Active JMX connections to C*",
   "type": "timeseries",
   "description": "This graph shows connection to Cassandra cluster pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "io_cassandrareaper_management_jmx_JmxManagementConnectionFactory_openJmxConnections{pod=~\"$pod\"}",
     "legendFormat": "pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Number of Opened Files",
   "type": "timeseries",
   "description": "Amount of opened files. Reaper takes snapshots of current segments. Write logs to files and store some information about run_history. Looks like they are faced with too many opened file descriptors issue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_openFiles_count{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}