{
 "title": "Cassandra TLP - JVM Overview",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "cassandra",
  "tlp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load,app_kubernetes_io_name)"
    }
   },
   {
    "name": "dc",
    "label": "Data Center",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load{app_kubernetes_io_name=\"$instance\"}, datacenter)"
    }
   },
   { "name": "pod", "label": "Pod", "query": { "query": "label_values(jvm_info, pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - sum(java_lang_OperatingSystem_FreePhysicalMemorySize{pod=~\"$pod\"}) / on(pod) sum(java_lang_OperatingSystem_TotalPhysicalMemorySize{pod=~\"$pod\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_TotalPhysicalMemorySize{pod=~\"$pod\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - sum(java_lang_OperatingSystem_FreeSwapSpaceSize{pod=~\"$pod\"}) / on(pod) sum(java_lang_OperatingSystem_TotalSwapSpaceSize{pod=~\"$pod\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_OperatingSystem_TotalSwapSpaceSize{pod=~\"$pod\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{pod=~\"$pod\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{pod=~\"$pod\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_OperatingSystem_AvailableProcessors{pod=~\"$pod\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{pod=~\"$pod\"} * 100",
     "legendFormat": "{{ pod }} system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{pod=~\"$pod\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ pod }} process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Heap/Non-Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\"}  / ignoring(area) group_left java_lang_OperatingSystem_TotalPhysicalMemorySize{pod=~\"$pod\"} * 100",
     "legendFormat": "{{ pod }} {{area}} memory"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pod=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ pod }} {{ pool }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} current"
    },
    {
     "expr": "jvm_threads_daemon{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} daemon"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{pod=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ pod }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage Collections (last minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_count{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }} {{ gc }}"
    }
   ]
  },
  {
   "title": "Average Time per GC (last five minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_collection_seconds_sum{pod=~\"$pod\"}[5m]) / on(pod, gc) delta(jvm_gc_collection_seconds_count{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }} {{ gc }}"
    }
   ]
  }
 ]
}