replicas: 1
container:
  image: cinple/mr-cassop/mr-cassop:0.5.0
  # imagePullSecret: container-registry-secret
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
logLevel: info
logFormat: json
proberImage: cinple/mr-cassop/prober:0.5.0 # this value will be updated on next release in GHA
jolokiaImage: cinple/mr-cassop/jolokia:0.5.0 # this value will be updated on next release in GHA
cassandraImage: cinple/mr-cassop/cassandra:3.11.13-0.5.0 # this value will be updated on next release in GHA
reaperImage: thelastpickle/cassandra-reaper:3.2.0
icarusImage: cinple/mr-cassop/icarus:0.5.0
clusterDashboards:
  enabled: []
  namespace: ""
  labels:
    grafana_dashboard: "1"
monitoring:
  enabled: false
  grafanaDashboard:
    enabled: false
    namespace: ""
    labels:
      grafana_dashboard: "1"
    datasourceName: ""
  serviceMonitor:
    enabled: false
    namespace: ""
    labels:
      operator: mr-cassop
    scrapeInterval: 30s
admissionWebhooks:
  enabled: true
