replicas: 1
container:
  image: ghcr.io/cin/mr-cassop/operator:0.6.0
  # imagePullSecret: container-registry-secret
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
logLevel: info
logFormat: json
proberImage: ghcr.io/cin/mr-cassop/prober:0.6.0
jolokiaImage: ghcr.io/cin/mr-cassop/jolokia:0.6.0
cassandraImage: ghcr.io/cin/mr-cassop/cassandra:0.6.0
reaperImage: thelastpickle/cassandra-reaper:4.2.5
icarusImage: ghcr.io/cin/mr-cassop/icarus:0.6.0
clusterDashboards:
  enabled: []
  namespace: ""
  labels:
    grafana_dashboard: "1"
monitoring:
  enabled: false
  grafanaDashboard:
    enabled: false
    namespace: ""
    labels:
      grafana_dashboard: "1"
    datasourceName: ""
  serviceMonitor:
    enabled: false
    namespace: ""
    labels:
      operator: mr-cassop
    scrapeInterval: 30s
admissionWebhooks:
  enabled: true
